<?php

namespace Bibliotheque\Bundle\BiblioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends EntityRepository
{
    public function getPersonnesByType($type){
        $qb= $this->createQueryBuilder('a')
            ->join('a.type_personne','typeP', 'WITH', 'typeP.type = :param1')
            ->setParameter('param1', $type)
        ;


        return $qb->getQuery()->getResult();
    }
}
